language: java
sudo: required

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: backend/target/Startreker-Netcracker-v1.jar
  skip_cleanup: true
  on:
    branch: master
    tags: true

before_deploy:
      - git config --local user.name "EugeneLokotariev"
      - git config --local user.email "evgenlokotarov@gmaill.com"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: eugenelokotariev-github
    token:
      secure: $SONAR_TOKEN

script:
  - mvn install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar