language: java
sudo: false
deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: "backend-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    branch: master

script:
  - mvn clean verify
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)