language: java

sudo: false

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: backend/target/Startreker-Netcracker-v1.jar
  skip_cleanup: true
  on:
    branch: master

instal: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: eugenelokotariev-github
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar